name: publish-docker

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64
        # platforms: linux/arm64,linux/arm/v6,linux/arm/v7

    - name: Set up Docker Buildx to support multiple architectures
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        # platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8

    - name: Build amd64 for testing
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: nuvious/proxpi:${{ github.ref_name }}
        platforms: linux/amd64
      
    - name: Run unit-tests in image for amd64
      run: docker run
        --rm
        --volume "$(pwd)/tests:/srv/tests"
        --entrypoint ''
        "nuvious/proxpi:${{ github.ref_name }}"
        sh -c 'pip install --requirement /srv/tests/requirements.txt
        && pytest -vvra /srv/tests'
    - name: Run image test
      run: tests/test-docker-image.sh "nuvious/proxpi:${{ github.ref_name }}"

    - name: Build arm64 for testing
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: nuvious/proxpi:${{ github.ref_name }}
        platforms: linux/arm64
        push: false

    - name: Run arm64 tests
      uses: addnab/docker-run-action@v3
      with:
        image: "nuvious/proxpi:${{ github.ref_name }}"
        options: |
          --platform linux/arm64
          --volume "$(pwd)/tests:/srv/tests"
          --entrypoint ''
        run: |
          uname -m
          pip install --requirement /srv/tests/requirements.txt
          pytest -vvra /srv/tests
        shell: sh
    
    - name: Login to DockerHub
      run: >
        echo ${{ secrets.DOCKERHUB_PASSWORD }}
        | docker login --password-stdin -u nuvious

    - name: Push all architectures
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        # platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        push: true
        tags: nuvious/proxpi:${{ github.ref_name }},nuvious/proxpi:latest
